export const COLORS = {
  WHITE_CHALK: '#F6F4F1',
  SILVER_HAZE: '#E2E4E7',
  PRAIRIE_LAND: '#E2CC92',
  TOMATO_CURRY: '#E84A2E',
  COSMIC_BLACK: '#0A0D0F',
  CELESTIAL_CANVAS: '#0A2538',
} as const;
